/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : DPI
 #	author : miyako
 #	2016/02/03
 #
 # --------------------------------------------------------------------------------*/

// --- DPI
void GET_SCREEN_DPI(sLONG_PTR *pResult, PackagePtr pParams);
